# goal definition
string command 	# “forward”,”turn_left”, “turn_right”
int32 s 			# расстояние в метрах которое должна проехать черепаха
int32 angle 		# угол в градусах на который должна повернуть черепаха
---
# result definition
bool result 		# true - черепаха выполнила команду, false - черепаха не смогла выполнить команду, например потому что выполнение команды прервали
---
#feedback
int32 odom 		# пройденное черепахой расстояние в метрах с момента начала выполнения команды